package com.aek.service.transfer.impl;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;

import com.aek.common.datasource.DataSource;
import com.aek.persistence.mysql.mapper.MSdHplStockOutItemsMapper;
import com.aek.persistence.oracle.beans.SdHplStockOutItems;
import com.aek.persistence.oracle.mapper.OSdHplStockOutItemsMapper;
import com.aek.service.transfer.SdHplStockOutItemsService;
import com.mb.common.util.ObjectUtils;

/**
 * 库房出库明细。操作服务实现类
 * @author Lanpz
 * @date 2016-12-20
 * @source Generated by MySQL2Java
 */
@Transactional(rollbackFor = Exception.class)
@Service("sdHplStockOutItemsService")
public class SdHplStockOutItemsServiceImpl implements SdHplStockOutItemsService {
    
    @Autowired
    private MSdHplStockOutItemsMapper mSdHplStockOutItemsMapper;
    
    @Autowired
    private OSdHplStockOutItemsMapper oSdHplStockOutItemsMapper;

    @DataSource(name = DataSource.mysql)
    @Override
    public List<SdHplStockOutItems> getMysqlList(Integer begin, Integer end, Integer dateFlag) {
        return mSdHplStockOutItemsMapper.getItemList(begin, end, dateFlag);
    }

    @DataSource(name = DataSource.oracle)
    @Override
    public List<SdHplStockOutItems> getOracle(List<SdHplStockOutItems> mysqlList) {
        return oSdHplStockOutItemsMapper.getItemList(mysqlList);
    }

    @DataSource(name = DataSource.oracle)
    @Override
    public void copyMysql2Oracle(List<SdHplStockOutItems> mysqlList, List<SdHplStockOutItems> oracleList) {
        List<SdHplStockOutItems> updateList = new ArrayList<SdHplStockOutItems>();

        List<SdHplStockOutItems> addList = new ArrayList<SdHplStockOutItems>();
        addList.addAll(mysqlList);
        if (ObjectUtils.isNotEmpty(mysqlList)) {
            if (ObjectUtils.isNotEmpty(oracleList)) {
                Iterator<SdHplStockOutItems> iterator = addList.iterator();
                
                // 查出需要添加和修改的数据信息放到列表中
                while (iterator.hasNext()) {
                    SdHplStockOutItems oracle = iterator.next();
                    Iterator<SdHplStockOutItems> oracleIt = oracleList.iterator();
                    while(oracleIt.hasNext()) {
                        SdHplStockOutItems mysql = oracleIt.next();
                        if (oracle.getItemId().equals(mysql.getItemId())) {
                            if (!oracle.toString().equals(mysql.toString())) {
                                updateList.add(oracle);
                            }
                            iterator.remove();
                            oracleIt.remove();
                            break;
                        }
                    }
                }
            }
            int addModifyNum = 0;
            if (addList != null && addList.size() > 0) {
                    addModifyNum = this.oSdHplStockOutItemsMapper.insertList(addList);
            }
            int updateModifyNum = 0;
            if (updateList != null && updateList.size() > 0) {
                updateModifyNum = this.oSdHplStockOutItemsMapper.updateList(updateList);
            }
        }
    }

    @DataSource(name = DataSource.oracle)
    @Override
    public int getOracleCount() {
        return oSdHplStockOutItemsMapper.getCount();
    }

}
