package com.aek.persistence.oracle.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.BdHplGoodses;
import com.mb.common.dal.BaseMapper;

/**
 * 物资基础数据表。Mapper
 * @author Lanpz
 * @date 2016-12-15
 * @source Generated by MySQL2Java
 */
@Repository
public interface OHplGoodsesMapper extends BaseMapper<BdHplGoodses, Integer> {

    List<BdHplGoodses> getGoodsList(List<BdHplGoodses> mysqlList);
    
    int insertList(List<BdHplGoodses> addList);
    
    int updateList(List<BdHplGoodses> updateList);

    int getCount();
}
