package com.aek.persistence.oracle.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.ZyChargeInterface;
import com.mb.common.dal.BaseMapper;

/**
 * 病人收费信息Mapper
 * @author Lanpz
 * @date 2016-08-04
 * @source Generated by MySQL2Java
 */
@Repository
public interface OZyChargeInterfaceMapper extends BaseMapper<ZyChargeInterface, Integer> {

    /**
     * 获取病人收费信息
     * @param mysqlList 
     * @param zyChargeInfo
     * @return List<ZyChargeInfo>
     */
    List<ZyChargeInterface> getList(List<ZyChargeInterface> mysqlList);
    
    int addList(List<ZyChargeInterface> addList) throws Exception;
    
    int updateList(List<ZyChargeInterface> updateList);
    
    int update(ZyChargeInterface oracle);
}
