package com.aek.service.transfer;

import java.util.List;

import com.aek.persistence.oracle.beans.BdHplGoodses;

/**
 * 物资基础数据。操作服务接口
 * @author Lanpz
 * @date 2016-12-15
 * @source Generated by MySQL2Java
 */
public interface HplGoodsesService {

    /**
     * 获取mysql库中产品信息
     * @param begin
     * @param end
     * @return
     */
    List<BdHplGoodses> getMysqlList(Integer begin, Integer end, Integer dateFlag);
    
    /**
     * 获取oracle库中产品信息
     * @param mysqlList
     * @return
     */
    List<BdHplGoodses> getOracleList(List<BdHplGoodses> mysqlList); 
    
    /**
     * 复制mysql的列表信息到oracle数据库中
     * @param mysqlList
     * @param oracleList
     * @return
     */
    int copyMysql2Oracle(List<BdHplGoodses> mysqlList, List<BdHplGoodses> oracleList);

    /**
     * 获取物资信息
     * @return
     */
    int getOracleCount();
}
