package com.aek.persistence.mysql.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.BdHplGoodsSpecs;
import com.mb.common.dal.BaseMapper;

/**
 * 物资规格表。Mapper
 * @author Lanpz
 * @date 2016-12-15
 * @source Generated by MySQL2Java
 */
@Repository
public interface MHplGoodsSpecsMapper extends BaseMapper<BdHplGoodsSpecs, Integer> {

    /**
     * 获取规格列表信息
     * @param begin
     * @param end
     * @return
     */
    List<BdHplGoodsSpecs> getSpecList(@Param("begin")Integer begin, @Param("end")Integer end, @Param("dateFlag")Integer dateFlag);

}
