package com.aek.persistence.oracle.beans;

import com.mb.common.dal.object.AbstractDO;

/**
 * 医疗收费代码视图模型
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
public class HisFeeInfo extends AbstractDO {

    /**
     * 收费代码
     */
    private String feeNo;

    /**
     * 收费名称
     */
    private String feeName;

    /**
     * 收费名称拼音码
     */
    private String feeNamePy;

    /**
     * 收费名称五笔码
     */
    private String feeNameWb;

    /**
     * 收费单价
     */
    private Double unitPrice;

    /**
     * 收费单位
     */
    private String feeUnit;

    /**
     * 类型(同时是手术名称)
     */
    private Integer feeType;

    /**
     * 取值 收费代码
     * @return 收费代码
     */
    public String getFeeNo() {
        return this.feeNo;
    }

    /**
     * 赋值 收费代码
     * @param feeNo 收费代码
     */
    public void setFeeNo(String feeNo) {
        this.feeNo = feeNo;
    }

    /**
     * 取值 收费名称
     * @return 收费名称
     */
    public String getFeeName() {
        return this.feeName;
    }

    /**
     * 赋值 收费名称
     * @param feeName 收费名称
     */
    public void setFeeName(String feeName) {
        this.feeName = feeName;
    }

    /**
     * 取值 收费名称拼音码
     * @return 收费名称拼音码
     */
    public String getFeeNamePy() {
        return this.feeNamePy;
    }

    /**
     * 赋值 收费名称拼音码
     * @param feeNamePy 收费名称拼音码
     */
    public void setFeeNamePy(String feeNamePy) {
        this.feeNamePy = feeNamePy;
    }

    /**
     * 取值 收费名称五笔码
     * @return 收费名称五笔码
     */
    public String getFeeNameWb() {
        return this.feeNameWb;
    }

    /**
     * 赋值 收费名称五笔码
     * @param feeNameWb 收费名称五笔码
     */
    public void setFeeNameWb(String feeNameWb) {
        this.feeNameWb = feeNameWb;
    }

    /**
     * 取值 收费单价
     * @return 收费单价
     */
    public Double getUnitPrice() {
        return this.unitPrice;
    }

    /**
     * 赋值 收费单价
     * @param unitPrice 收费单价
     */
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * 取值 收费单位
     * @return 收费单位
     */
    public String getFeeUnit() {
        return this.feeUnit;
    }

    /**
     * 赋值 收费单位
     * @param feeUnit 收费单位
     */
    public void setFeeUnit(String feeUnit) {
        this.feeUnit = feeUnit;
    }

    /**
     * 取值 类型(同时是手术名称)
     * @return 类型(同时是手术名称)
     */
    public Integer getFeeType() {
        return this.feeType;
    }

    /**
     * 赋值 类型(同时是手术名称)
     * @param feeType 类型(同时是手术名称)
     */
    public void setFeeType(Integer feeType) {
        this.feeType = feeType;
    }

}
