package com.aek.persistence.oracle.beans;

import com.mb.common.dal.object.AbstractDO;

/**
 * HIS职工人员视图模型
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
public class HisUserInfo extends AbstractDO {

    /**
     * 职工工号
     */
    private String userNo;

    /**
     * 职工名称
     */
    private String userName;

    /**
     * 职工名称拼音码
     */
    private String userNamePy;

    /**
     * 职工名称五笔码
     */
    private String userNameWb;

    /**
     * 职工性别1:男 0:女
     */
    private Integer userSex;

    /**
     * 科室代码
     */
    private String userDeptNo;

    /**
     * 作废标志
     */
    private Integer delFlag;

    /**
     * 取值 职工工号
     * @return 职工工号
     */
    public String getUserNo() {
        return this.userNo;
    }

    /**
     * 赋值 职工工号
     * @param userNo 职工工号
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo;
    }

    /**
     * 取值 职工名称
     * @return 职工名称
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * 赋值 职工名称
     * @param userName 职工名称
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * 取值 职工名称拼音码
     * @return 职工名称拼音码
     */
    public String getUserNamePy() {
        return this.userNamePy;
    }

    /**
     * 赋值 职工名称拼音码
     * @param userNamePy 职工名称拼音码
     */
    public void setUserNamePy(String userNamePy) {
        this.userNamePy = userNamePy;
    }

    /**
     * 取值 职工名称五笔码
     * @return 职工名称五笔码
     */
    public String getUserNameWb() {
        return this.userNameWb;
    }

    /**
     * 赋值 职工名称五笔码
     * @param userNameWb 职工名称五笔码
     */
    public void setUserNameWb(String userNameWb) {
        this.userNameWb = userNameWb;
    }

    /**
     * 取值 职工性别1:男 0:女
     * @return 职工性别1:男 0:女
     */
    public Integer getUserSex() {
        return this.userSex;
    }

    /**
     * 赋值 职工性别1:男 0:女
     * @param userSex 职工性别1:男 0:女
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * 取值 科室代码
     * @return 科室代码
     */
    public String getUserDeptNo() {
        return this.userDeptNo;
    }

    /**
     * 赋值 科室代码
     * @param userDeptNo 科室代码
     */
    public void setUserDeptNo(String userDeptNo) {
        this.userDeptNo = userDeptNo;
    }

    /**
     * 取值 作废标志
     * @return 作废标志
     */
    public Integer getDelFlag() {
        return this.delFlag;
    }

    /**
     * 赋值 作废标志
     * @param delFlag 作废标志
     */
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

}
