package com.aek.persistence.oracle.beans;

import java.util.Date;

import com.mb.common.dal.object.AbstractDO;

/**
 * 病人收费信息模型
 * @author Lanpz
 * @date 2016-08-04
 * @source Generated by MySQL2Java
 */
public class ZyChargeInterface extends AbstractDO {

    /**
     * 序号
     */
    private Integer id;

    /**
     * 原序号
     */
    private Integer oldid;

    /**
     * 就诊卡号
     */
    private String medicardno;

    /**
     * 病人序号(对应病案号)
     */
    private Integer patientno;

    /**
     * 婴儿标志  0：大人费用  1:婴儿费用
     */
    private Integer infantflag;

    /**
     * 收费项目编号 (诊疗必填,对应医疗收费
     */
    private Integer chargecode;

    /**
     * 收费项目名称 (诊疗必填,对应
     */
    private String chargename;

    /**
     * 系统类别  (必填(YYF),对应
     */
    private String systemtype;

    /**
     * 系统纪录序号
     */
    private String systemid;

    /**
     * 发生日期
     */
    private Date chargedate;

    /**
     * 数量       (必填,对应zy_detail_charge.sl)
     */
    private Double amount;

    /**
     * 单价        (必填,对应zy_detail_charge.dj)
     */
    private Double price;

    /**
     * 金额
     */
    private Double fee;

    /**
     * 医生工号     (必填,对应
     */
    private String doctorid;

    /**
     * 执行科室     (必填,对应
     */
    private String executdept;

    /**
     * 入住病区     (必填,对应
     */
    private String admisssickroom;

    /**
     * 入住科室     (必填,对应
     */
    private String admisssickdept;

    /**
     * 操作工号     (必填,对应
     */
    private String operatid;

    /**
     * 复核工号     (必填,对应
     */
    private String auditid;

    /**
     * 传送标志  (必填，填0)0:未采集  1:已采集
     */
    private Integer sendflag;

    /**
     * 门诊、住院标志 0:门诊  1:住院(必填)
     */
    private Integer beinhosflag;

    /**
     * 操作日期(必填，填录入费用时的日期)
     */
    private Date operatedate;

    /**
     * 互助金标记(必填，填null)
     */
    private String concurflag;

    /**
     * 发票号码
     */
    private String invoiceNo;

    /**
     * 发票医生工号
     */
    private String invoiceDoctorcode;

    /**
     * 发票产生日期
     */
    private Date invoiceChargedate;

    /**
     * 报销日期
     */
    private Date bxDate;

    /**
     * 药品产地代码  (药品必填,对应
     */
    private Integer ypcddm;

    /**
     * 药品序号      (药品必填,对应
     */
    private Integer ypxh;

    /**
     * 套餐代码 (如果是套餐里的细项时必填，,对应
     */
    private String tcdm;

    /**
     * 诊疗医保代码，指材料项目的诊疗适应症
     */
    private String zlybdm;

    /**
     * 分院编号   (必填，0：总院，1：爱德分院)
     */
    private Integer fybh;
    

    /**
     * 取值 序号
     * @return 序号
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 赋值 序号
     * @param id 序号
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 取值 原序号
     * @return 原序号
     */
    public Integer getOldid() {
        return this.oldid;
    }

    /**
     * 赋值 原序号
     * @param oldid 原序号
     */
    public void setOldid(Integer oldid) {
        this.oldid = oldid;
    }

    /**
     * 取值 就诊卡号
     * @return 就诊卡号
     */
    public String getMedicardno() {
        return this.medicardno;
    }

    /**
     * 赋值 就诊卡号
     * @param medicardno 就诊卡号
     */
    public void setMedicardno(String medicardno) {
        this.medicardno = medicardno;
    }

    /**
     * 取值 病人序号(对应病案号)
     * @return 病人序号(对应病案号)
     */
    public Integer getPatientno() {
        return this.patientno;
    }

    /**
     * 赋值 病人序号(对应病案号)
     * @param patientno 病人序号(对应病案号)
     */
    public void setPatientno(Integer patientno) {
        this.patientno = patientno;
    }

    /**
     * 取值 婴儿标志  0：大人费用  1:婴儿费用
     * @return 婴儿标志  0：大人费用  1:婴儿费用
     */
    public Integer getInfantflag() {
        return this.infantflag;
    }

    /**
     * 赋值 婴儿标志  0：大人费用  1:婴儿费用
     * @param infantflag 婴儿标志  0：大人费用  1:婴儿费用
     */
    public void setInfantflag(Integer infantflag) {
        this.infantflag = infantflag;
    }

    /**
     * 取值 收费项目编号 (诊疗必填,对应医疗收费
     * @return 收费项目编号 (诊疗必填,对应医疗收费
     */
    public Integer getChargecode() {
        return this.chargecode;
    }

    /**
     * 赋值 收费项目编号 (诊疗必填,对应医疗收费
     * @param chargecode 收费项目编号 (诊疗必填,对应医疗收费
     */
    public void setChargecode(Integer chargecode) {
        this.chargecode = chargecode;
    }

    /**
     * 取值 收费项目名称 (诊疗必填,对应
     * @return 收费项目名称 (诊疗必填,对应
     */
    public String getChargename() {
        return this.chargename;
    }

    /**
     * 赋值 收费项目名称 (诊疗必填,对应
     * @param chargename 收费项目名称 (诊疗必填,对应
     */
    public void setChargename(String chargename) {
        this.chargename = chargename;
    }

    /**
     * 取值 系统类别  (必填(YYF),对应
     * @return 系统类别  (必填(YYF),对应
     */
    public String getSystemtype() {
        return this.systemtype;
    }

    /**
     * 赋值 系统类别  (必填(YYF),对应
     * @param systemtype 系统类别  (必填(YYF),对应
     */
    public void setSystemtype(String systemtype) {
        this.systemtype = systemtype;
    }

    /**
     * 取值 系统纪录序号
     * @return 系统纪录序号
     */
    public String getSystemid() {
        return this.systemid;
    }

    /**
     * 赋值 系统纪录序号
     * @param systemid 系统纪录序号
     */
    public void setSystemid(String systemid) {
        this.systemid = systemid;
    }

    /**
     * 取值 发生日期
     * @return 发生日期
     */
    public Date getChargedate() {
        return this.chargedate;
    }

    /**
     * 赋值 发生日期
     * @param chargedate 发生日期
     */
    public void setChargedate(Date chargedate) {
        this.chargedate = chargedate;
    }

    /**
     * 取值 数量       (必填,对应zy_detail_charge.sl)
     * @return 数量       (必填,对应zy_detail_charge.sl)
     */
    public Double getAmount() {
        return this.amount;
    }

    /**
     * 赋值 数量       (必填,对应zy_detail_charge.sl)
     * @param amount 数量       (必填,对应zy_detail_charge.sl)
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * 取值 单价        (必填,对应zy_detail_charge.dj)
     * @return 单价        (必填,对应zy_detail_charge.dj)
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * 赋值 单价        (必填,对应zy_detail_charge.dj)
     * @param price 单价        (必填,对应zy_detail_charge.dj)
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * 取值 金额
     * @return 金额
     */
    public Double getFee() {
        return this.fee;
    }

    /**
     * 赋值 金额
     * @param fee 金额
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }

    /**
     * 取值 医生工号     (必填,对应
     * @return 医生工号     (必填,对应
     */
    public String getDoctorid() {
        return this.doctorid;
    }

    /**
     * 赋值 医生工号     (必填,对应
     * @param doctorid 医生工号     (必填,对应
     */
    public void setDoctorid(String doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * 取值 执行科室     (必填,对应
     * @return 执行科室     (必填,对应
     */
    public String getExecutdept() {
        return this.executdept;
    }

    /**
     * 赋值 执行科室     (必填,对应
     * @param executdept 执行科室     (必填,对应
     */
    public void setExecutdept(String executdept) {
        this.executdept = executdept;
    }

    /**
     * 取值 入住病区     (必填,对应
     * @return 入住病区     (必填,对应
     */
    public String getAdmisssickroom() {
        return this.admisssickroom;
    }

    /**
     * 赋值 入住病区     (必填,对应
     * @param admisssickroom 入住病区     (必填,对应
     */
    public void setAdmisssickroom(String admisssickroom) {
        this.admisssickroom = admisssickroom;
    }

    /**
     * 取值 入住科室     (必填,对应
     * @return 入住科室     (必填,对应
     */
    public String getAdmisssickdept() {
        return this.admisssickdept;
    }

    /**
     * 赋值 入住科室     (必填,对应
     * @param admisssickdept 入住科室     (必填,对应
     */
    public void setAdmisssickdept(String admisssickdept) {
        this.admisssickdept = admisssickdept;
    }

    /**
     * 取值 操作工号     (必填,对应
     * @return 操作工号     (必填,对应
     */
    public String getOperatid() {
        return this.operatid;
    }

    /**
     * 赋值 操作工号     (必填,对应
     * @param operatid 操作工号     (必填,对应
     */
    public void setOperatid(String operatid) {
        this.operatid = operatid;
    }

    /**
     * 取值 复核工号     (必填,对应
     * @return 复核工号     (必填,对应
     */
    public String getAuditid() {
        return this.auditid;
    }

    /**
     * 赋值 复核工号     (必填,对应
     * @param auditid 复核工号     (必填,对应
     */
    public void setAuditid(String auditid) {
        this.auditid = auditid;
    }

    /**
     * 取值 传送标志  (必填，填0)0:未采集  1:已采集
     * @return 传送标志  (必填，填0)0:未采集  1:已采集
     */
    public Integer getSendflag() {
        return this.sendflag;
    }

    /**
     * 赋值 传送标志  (必填，填0)0:未采集  1:已采集
     * @param sendflag 传送标志  (必填，填0)0:未采集  1:已采集
     */
    public void setSendflag(Integer sendflag) {
        this.sendflag = sendflag;
    }

    /**
     * 取值 门诊、住院标志 0:门诊  1:住院(必填)
     * @return 门诊、住院标志 0:门诊  1:住院(必填)
     */
    public Integer getBeinhosflag() {
        return this.beinhosflag;
    }

    /**
     * 赋值 门诊、住院标志 0:门诊  1:住院(必填)
     * @param beinhosflag 门诊、住院标志 0:门诊  1:住院(必填)
     */
    public void setBeinhosflag(Integer beinhosflag) {
        this.beinhosflag = beinhosflag;
    }

    /**
     * 取值 操作日期(必填，填录入费用时的日期)
     * @return 操作日期(必填，填录入费用时的日期)
     */
    public Date getOperatedate() {
        return this.operatedate;
    }

    /**
     * 赋值 操作日期(必填，填录入费用时的日期)
     * @param operatedate 操作日期(必填，填录入费用时的日期)
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * 取值 互助金标记(必填，填null)
     * @return 互助金标记(必填，填null)
     */
    public String getConcurflag() {
        return this.concurflag;
    }

    /**
     * 赋值 互助金标记(必填，填null)
     * @param concurflag 互助金标记(必填，填null)
     */
    public void setConcurflag(String concurflag) {
        this.concurflag = concurflag;
    }

    /**
     * 取值 发票号码
     * @return 发票号码
     */
    public String getInvoiceNo() {
        return this.invoiceNo;
    }

    /**
     * 赋值 发票号码
     * @param invoiceNo 发票号码
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    /**
     * 取值 发票医生工号
     * @return 发票医生工号
     */
    public String getInvoiceDoctorcode() {
        return this.invoiceDoctorcode;
    }

    /**
     * 赋值 发票医生工号
     * @param invoiceDoctorcode 发票医生工号
     */
    public void setInvoiceDoctorcode(String invoiceDoctorcode) {
        this.invoiceDoctorcode = invoiceDoctorcode;
    }

    /**
     * 取值 发票产生日期
     * @return 发票产生日期
     */
    public Date getInvoiceChargedate() {
        return this.invoiceChargedate;
    }

    /**
     * 赋值 发票产生日期
     * @param invoiceChargedate 发票产生日期
     */
    public void setInvoiceChargedate(Date invoiceChargedate) {
        this.invoiceChargedate = invoiceChargedate;
    }

    /**
     * 取值 报销日期
     * @return 报销日期
     */
    public Date getBxDate() {
        return this.bxDate;
    }

    /**
     * 赋值 报销日期
     * @param bxDate 报销日期
     */
    public void setBxDate(Date bxDate) {
        this.bxDate = bxDate;
    }

    /**
     * 取值 药品产地代码  (药品必填,对应
     * @return 药品产地代码  (药品必填,对应
     */
    public Integer getYpcddm() {
        return this.ypcddm;
    }

    /**
     * 赋值 药品产地代码  (药品必填,对应
     * @param ypcddm 药品产地代码  (药品必填,对应
     */
    public void setYpcddm(Integer ypcddm) {
        this.ypcddm = ypcddm;
    }

    /**
     * 取值 药品序号      (药品必填,对应
     * @return 药品序号      (药品必填,对应
     */
    public Integer getYpxh() {
        return this.ypxh;
    }

    /**
     * 赋值 药品序号      (药品必填,对应
     * @param ypxh 药品序号      (药品必填,对应
     */
    public void setYpxh(Integer ypxh) {
        this.ypxh = ypxh;
    }

    /**
     * 取值 套餐代码 (如果是套餐里的细项时必填，,对应
     * @return 套餐代码 (如果是套餐里的细项时必填，,对应
     */
    public String getTcdm() {
        return this.tcdm;
    }

    /**
     * 赋值 套餐代码 (如果是套餐里的细项时必填，,对应
     * @param tcdm 套餐代码 (如果是套餐里的细项时必填，,对应
     */
    public void setTcdm(String tcdm) {
        this.tcdm = tcdm;
    }

    /**
     * 取值 诊疗医保代码，指材料项目的诊疗适应症
     * @return 诊疗医保代码，指材料项目的诊疗适应症
     */
    public String getZlybdm() {
        return this.zlybdm;
    }

    /**
     * 赋值 诊疗医保代码，指材料项目的诊疗适应症
     * @param zlybdm 诊疗医保代码，指材料项目的诊疗适应症
     */
    public void setZlybdm(String zlybdm) {
        this.zlybdm = zlybdm;
    }

    /**
     * 取值 分院编号   (必填，0：总院，1：爱德分院)
     * @return 分院编号   (必填，0：总院，1：爱德分院)
     */
    public Integer getFybh() {
        return this.fybh;
    }

    /**
     * 赋值 分院编号   (必填，0：总院，1：爱德分院)
     * @param fybh 分院编号   (必填，0：总院，1：爱德分院)
     */
    public void setFybh(Integer fybh) {
        this.fybh = fybh;
    }

}
