package com.aek.persistence.oracle.beans;

import com.mb.common.dal.object.AbstractDO;

/**
 * 模型
 * @author Lanpz
 * @date 2016-08-04
 * @source Generated by MySQL2Java
 */
public class ZyDetailCharge extends AbstractDO {
    /**
     * 住院号
     */
    private Integer patientNo;

    /**
     * 收费代码
     */
    private Integer chargeCode;

    /**
     * 收费名称
     */
    private String chargeName;

    /**
     * 收费日期
     */
    private String chargeDate;

    /**
     * 数量
     */
    private Integer sl;

    /**
     * 单价
     */
    private Integer dj;

    /**
     * 类型(1:联动 2:手工)
     */
    private Integer type;

    /**
     * 适应症代码,
     */
    private String indicationNo;

    /**
     * 适应症名称
     */
    private String indicationName;

    /**
     * 执行科室代码
     */
    private String deptNo;

    /**
     * 收费明细id
     */
    private Integer chargeId;
    

    /**
     * 取值 住院号
     * @return 住院号
     */
    public Integer getPatientNo() {
        return this.patientNo;
    }

    /**
     * 赋值 住院号
     * @param patientNo 住院号
     */
    public void setPatientNo(Integer patientNo) {
        this.patientNo = patientNo;
    }

    /**
     * 取值 收费代码
     * @return 收费代码
     */
    public Integer getChargeCode() {
        return this.chargeCode;
    }

    /**
     * 赋值 收费代码
     * @param chargeCode 收费代码
     */
    public void setChargeCode(Integer chargeCode) {
        this.chargeCode = chargeCode;
    }

    /**
     * 取值 收费名称
     * @return 收费名称
     */
    public String getChargeName() {
        return this.chargeName;
    }

    /**
     * 赋值 收费名称
     * @param chargeName 收费名称
     */
    public void setChargeName(String chargeName) {
        this.chargeName = chargeName;
    }

    /**
     * 取值 收费日期
     * @return 收费日期
     */
    public String getChargeDate() {
        return this.chargeDate;
    }

    /**
     * 赋值 收费日期
     * @param chargeDate 收费日期
     */
    public void setChargeDate(String chargeDate) {
        this.chargeDate = chargeDate;
    }

    /**
     * 取值 数量
     * @return 数量
     */
    public Integer getSl() {
        return this.sl;
    }

    /**
     * 赋值 数量
     * @param sl 数量
     */
    public void setSl(Integer sl) {
        this.sl = sl;
    }

    /**
     * 取值 单价
     * @return 单价
     */
    public Integer getDj() {
        return this.dj;
    }

    /**
     * 赋值 单价
     * @param dj 单价
     */
    public void setDj(Integer dj) {
        this.dj = dj;
    }

    /**
     * 取值 类型(1:联动 2:手工)
     * @return 类型(1:联动 2:手工)
     */
    public Integer getType() {
        return this.type;
    }

    /**
     * 赋值 类型(1:联动 2:手工)
     * @param type 类型(1:联动 2:手工)
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * 取值 适应症代码,
     * @return 适应症代码,
     */
    public String getIndicationNo() {
        return this.indicationNo;
    }

    /**
     * 赋值 适应症代码,
     * @param indicationNo 适应症代码,
     */
    public void setIndicationNo(String indicationNo) {
        this.indicationNo = indicationNo;
    }

    /**
     * 取值 适应症名称
     * @return 适应症名称
     */
    public String getIndicationName() {
        return this.indicationName;
    }

    /**
     * 赋值 适应症名称
     * @param indicationName 适应症名称
     */
    public void setIndicationName(String indicationName) {
        this.indicationName = indicationName;
    }

    /**
     * 取值 执行科室代码
     * @return 执行科室代码
     */
    public String getDeptNo() {
        return this.deptNo;
    }

    /**
     * 赋值 执行科室代码
     * @param deptNo 执行科室代码
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * 取值 收费明细id
     * @return 收费明细id
     */
    public Integer getChargeId() {
        return this.chargeId;
    }

    /**
     * 赋值 收费明细id
     * @param chargeId 收费明细id
     */
    public void setChargeId(Integer chargeId) {
        this.chargeId = chargeId;
    }

}
