package com.aek.service.transfer;

import java.util.List;

import com.aek.persistence.oracle.beans.SdHplStockOut;

/**
 * 库房正常出库记录。操作服务接口
 * @author Lanpz
 * @date 2016-12-20
 * @source Generated by MySQL2Java
 */
public interface SdHplStockOutService {

    List<SdHplStockOut> getMysqlList(Integer begin, Integer end, Integer dateFlag);

    List<SdHplStockOut> getOracleList(List<SdHplStockOut> mysqlList);

    void copyMySql2Oracle(List<SdHplStockOut> mysqlList, List<SdHplStockOut> oracleList);

    int getOracleCount();

}
