package com.aek.service.transfer.impl;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.aek.common.datasource.DataSource;
import com.aek.persistence.mysql.mapper.MHplGoodsesMapper;
import com.aek.persistence.oracle.beans.BdHplGoodses;
import com.aek.persistence.oracle.mapper.OHplGoodsesMapper;
import com.aek.service.transfer.HplGoodsesService;
import com.mb.common.util.ObjectUtils;

/**
 * 物资基础数据。操作服务实现类
 * @author Lanpz
 * @date 2016-12-15
 * @source Generated by MySQL2Java
 */
@Transactional(rollbackFor = Exception.class)
@Service("hplGoodsesService")
public class HplGoodsesServiceImpl implements HplGoodsesService {

    @Autowired
    private MHplGoodsesMapper mHplGoodsesMapper;
    
    @Autowired
    private OHplGoodsesMapper oHplGoodsesMapper;
    
    @DataSource(name = DataSource.mysql)
    @Override
    public List<BdHplGoodses> getMysqlList(Integer begin, Integer end, Integer dateFlag) {
        return mHplGoodsesMapper.getGoodsList(begin, end, dateFlag);
    }

    @DataSource(name = DataSource.oracle)
    @Override
    public List<BdHplGoodses> getOracleList(List<BdHplGoodses> mysqlList) {
        return oHplGoodsesMapper.getGoodsList(mysqlList);
    }

    @DataSource(name = DataSource.oracle)
    @Override
    public int copyMysql2Oracle(List<BdHplGoodses> mysqlList, List<BdHplGoodses> oracleList) {
        List<BdHplGoodses> updateList = new ArrayList<BdHplGoodses>();

        List<BdHplGoodses> addList = new ArrayList<BdHplGoodses>();
        addList.addAll(mysqlList);
        if (ObjectUtils.isNotEmpty(mysqlList)) {
            if (ObjectUtils.isNotEmpty(oracleList)) {
                Iterator<BdHplGoodses> iterator = addList.iterator();
                
                // 查出需要添加和修改的数据信息放到列表中
                while (iterator.hasNext()) {
                    BdHplGoodses oracle = iterator.next();
                    Iterator<BdHplGoodses> oracleIt = oracleList.iterator();
                    while(oracleIt.hasNext()) {
                        BdHplGoodses mysql = oracleIt.next();
                        if (oracle.getGoodsId().equals(mysql.getGoodsId())) {
                            if (!oracle.toString().equals(mysql.toString())) {
                                updateList.add(oracle);
                            }
                            iterator.remove();
                            oracleIt.remove();
                            break;
                        }
                    }
                }
            }
            int addModifyNum = 0;
            if (addList != null && addList.size() > 0) {
                    addModifyNum = this.oHplGoodsesMapper.insertList(addList);
            }
            int updateModifyNum = 0;
            if (updateList != null && updateList.size() > 0) {
                updateModifyNum = this.oHplGoodsesMapper.updateList(updateList);
            }
            if (updateModifyNum >= 0 && addModifyNum == addList.size()) {
                return 1;
            }
        }

        return 0;
    }

    @DataSource(name = DataSource.oracle)
    @Override
    public int getOracleCount() {
        return oHplGoodsesMapper.getCount();
    }

    
}
