package com.aek.service.transfer;

import java.util.List;

import com.aek.persistence.oracle.beans.SdHplStockOutItems;

/**
 * 库房出库明细。操作服务接口
 * @author Lanpz
 * @date 2016-12-20
 * @source Generated by MySQL2Java
 */
public interface SdHplStockOutItemsService {

    List<SdHplStockOutItems> getMysqlList(Integer begin, Integer end, Integer dateFlag);

    List<SdHplStockOutItems> getOracle(List<SdHplStockOutItems> mysqlList);

    void copyMysql2Oracle(List<SdHplStockOutItems> mysqlList, List<SdHplStockOutItems> oracleList);

    int getOracleCount();

}
