package com.aek.persistence.mysql.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.HisInpatientInfo;
import com.mb.common.dal.BaseMapper;

/**
 * 手术病人信息视图Mapper
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
@Repository
public interface MHisInpatientInfoMapper extends BaseMapper<HisInpatientInfo, Integer> {

    /**
     * 获取手术病人信息视图
     * @param oracleList 
     * @param hisInpatientInfo
     * @return List<HisInpatientInfo>
     */
    List<HisInpatientInfo> getAll(List<HisInpatientInfo> oracleList);

    /**
     * 批量添加手术病人信息视图
     * @param addList
     * @return
     */
    int addList(List<HisInpatientInfo> addList);

    /**
     * 批量修改手术病人信息
     * @param updateList
     * @return
     */
    int updateList(List<HisInpatientInfo> updateList);

}
