package com.aek.persistence.mysql.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.HisDeptInfo;
import com.mb.common.dal.BaseMapper;

/**
 * 科室信息视图Mapper
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
@Repository
public interface MHisDeptInfoMapper extends BaseMapper<HisDeptInfo, Integer> {
    /**
     * 查找mysql库中所有科室信息
     * @param deptOracleList 
     * @return
     */
    List<HisDeptInfo> getAll(List<HisDeptInfo> deptOracleList);

    /**
     * 批量修改数据
     * @param updateList
     * @return
     */
    int updateList(List<HisDeptInfo> updateList);

    /**
     * 批量添加
     * @param addList
     * @return
     */
    Integer addList(List<HisDeptInfo> addList);

}
