package com.aek.persistence.oracle.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;
import com.aek.persistence.oracle.beans.BdHplGoodsSpecs;
import com.mb.common.dal.BaseMapper;

/**
 * 物资规格表。Mapper
 * @author Lanpz
 * @date 2016-12-15
 * @source Generated by MySQL2Java
 */
@Repository
public interface OHplGoodsSpecsMapper extends BaseMapper<BdHplGoodsSpecs, Integer> {
    /**
     * 根据mysql的列表信息查找oracle中是否存在数据
     * @param mysqlList
     * @return
     */
    List<BdHplGoodsSpecs> getSpecList(List<BdHplGoodsSpecs> mysqlList);
    
    /**
     * 插入规格信息
     * @param specList
     * @return
     */
    int insertList(List<BdHplGoodsSpecs> specList);
    
    /**
     * 修改规格信息
     * @param specList
     * @return
     */
    int updateList(List<BdHplGoodsSpecs> specList);

    /**
     * 获取oracle中物资规格列表的长度
     * @return
     */
    int getCount();
}
