package com.aek.persistence.oracle.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.ZyDetailCharge;
import com.mb.common.dal.BaseMapper;

/**
 * Mapper
 * @author Lanpz
 * @date 2016-08-04
 * @source Generated by MySQL2Java
 */
@Repository
public interface OZyDetailChargeMapper extends BaseMapper<ZyDetailCharge, Integer> {

    /**
     * 获取
     * @param end 
     * @param begin 
     * @param zyDetailCharge
     * @return List<ZyDetailCharge>
     */
   List<ZyDetailCharge> getZyDetailChargeList(@Param("begin")int begin, @Param("end")int end);
}
