package com.aek.persistence.oracle.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.SdHplStockOut;
import com.mb.common.dal.BaseMapper;

/**
 * 库房正常出库记录表。Mapper
 * 
 * @author Lanpz
 * @date 2016-12-20
 * @source Generated by MySQL2Java
 */
@Repository
public interface OSdHplStockOutMapper extends BaseMapper<SdHplStockOut, Integer> {
    List<SdHplStockOut> getList(List<SdHplStockOut> mysqlList);

    int insertList(List<SdHplStockOut> addList);

    int updateList(List<SdHplStockOut> updateList);

    int getCount();
}
