package com.aek.persistence.mysql.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.DataErrorInfo;
import com.mb.common.dal.BaseMapper;

/**
 * Mapper
 * @author Lanpz
 * @date 2016-08-05
 * @source Generated by MySQL2Java
 */
@Repository
public interface DataErrorInfoMapper extends BaseMapper<DataErrorInfo, Integer> {

    /**
     * 获取未成功的错误记录信息
     * @param dataErrorInfo
     * @return List<DataErrorInfo>
     */
    List<DataErrorInfo> getErrorList();

    /**
     * 获取待执行的错误记录信息
     * @param end 
     * @param begin 
     * @return
     */
    List<DataErrorInfo> getExcuteList(@Param("begin")int begin, @Param("end")int end);

    /**
     * 根据存放的id修改处理状态
     * @param id
     * @return
     */
    int updateByKey(Integer primaryKey);

    /**
     * 如果已出错数据再次出错进行修改操作
     * @param mysqlId
     * @return
     */
    int updateError(Integer mysqlId);

    int getErrorCount();

}
