package com.aek.persistence.oracle.beans;

import java.util.Date;

import com.mb.common.dal.object.AbstractDO;
import com.mb.common.util.DateUtils;

/**
 * 模型
 * @author Lanpz
 * @date 2016-08-05
 * @source Generated by MySQL2Java
 */
public class DataErrorInfo extends AbstractDO {

    /**
     * 主键
     */
    private Integer errorId;

    /**
     * 错误信息
     */
    private String errorMsg;

    /**
     * 异常时间
     */
    private String happenTime;

    /**
     * 表名
     */
    private String tableName;

    /**
     * 主键信息
     */
    private Integer primaryKey;

    /**
     * 执行时间
     */
    private Integer excuteTime;
    
    /**
     * 是否被解决
     */
    private Integer isSolved;

    /**
     * 取值 主键
     * @return 主键
     */
    public Integer getErrorId() {
        return this.errorId;
    }

    /**
     * 赋值 主键
     * @param errorId 主键
     */
    public void setErrorId(Integer errorId) {
        this.errorId = errorId;
    }

    /**
     * 取值 错误信息
     * @return 错误信息
     */
    public String getErrorMsg() {
        return this.errorMsg;
    }

    /**
     * 赋值 错误信息
     * @param errorMsg 错误信息
     */
    public void setErrorMsg(String errorMsg) {
        this.errorMsg = errorMsg;
    }

    /**
     * 取值 异常时间
     * @return 异常时间
     */
    public String getHappenTime() {
        return this.happenTime;
    }

    /**
     * 赋值 异常时间
     * @param happenTime 异常时间
     */
    public void setHappenTime(String happenTime) {
        this.happenTime = happenTime;
    }

    /**
     * 取值 表名
     * @return 表名
     */
    public String getTableName() {
        return this.tableName;
    }

    /**
     * 赋值 表名
     * @param tableName 表名
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * 取值 主键信息
     * @return 主键信息
     */
    public Integer getPrimaryKey() {
        return this.primaryKey;
    }

    /**
     * 赋值 主键信息
     * @param primaryKey 主键信息
     */
    public void setPrimaryKey(Integer primaryKey) {
        this.primaryKey = primaryKey;
    }

    /**
     * 取值 是否被解决
     * @return 是否被解决
     */
    public Integer getIsSolved() {
        return this.isSolved;
    }

    /**
     * 赋值 是否被解决
     * @param isSolved 是否被解决
     */
    public void setIsSolved(Integer isSolved) {
        this.isSolved = isSolved;
    }

    public Integer getExcuteTime() {
        return excuteTime;
    }

    public void setExcuteTime(Integer excuteTime) {
        this.excuteTime = excuteTime;
    }
}
