package com.aek.persistence.mysql.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.ZyDetailCharge;
import com.mb.common.dal.BaseMapper;

/**
 * Mapper
 * 
 * @author Lanpz
 * @date 2016-08-04
 * @source Generated by MySQL2Java
 */
@Repository
public interface MZyDetailChargeMapper extends BaseMapper<ZyDetailCharge, Integer> {

    /**
     * 获取
     * @param detailOracleList 
     * 
     * @param zyDetailCharge
     * @return List<ZyDetailCharge>
     */
    List<ZyDetailCharge> getZyDetailChargeList(List<ZyDetailCharge> detailOracleList);

    int addList(List<ZyDetailCharge> addList);

    int updateList(List<ZyDetailCharge> updateList);
}
