package com.aek.persistence.oracle.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.SdHplStockOutItems;
import com.mb.common.dal.BaseMapper;

/**
 * 库房出库明细表。Mapper
 * @author Lanpz
 * @date 2016-12-20
 * @source Generated by MySQL2Java
 */
@Repository
public interface OSdHplStockOutItemsMapper extends BaseMapper<SdHplStockOutItems, Integer> {
    List<SdHplStockOutItems> getItemList(List<SdHplStockOutItems> mysqlList);
    
    int insertList(List<SdHplStockOutItems> addList);
    
    int updateList(List<SdHplStockOutItems> updateList);

    int getCount();
}
