package com.aek.persistence.oracle.beans;

import com.mb.common.dal.object.AbstractDO;

/**
 * 物资规格表。模型
 * @author Lanpz
 * @date 2016-12-15
 * @source Generated by MySQL2Java
 */
public class BdHplGoodsSpecs extends AbstractDO {
    private Long specId;

    private Long sysId;
    private Integer areaId;
    private Long classId;
    
    private String className;

    private Long goodsId;
    
    private String goodsName;

    private Integer goodsType;
    
    private String specGuid;

    private String specNo;

    private String specBarcode;

    private Integer specBarcodeType;
    private String specModel;
    private String specCommonName;

    private String specNameEn;

    private String specNameCn;

    private String specPackage;

    private String specBigpackstr;

    private String specBasepackstr;

    private Integer specBasepackNo;

    private String specBasepackNote;

    private String specMinipackstr;

    private Double specMiniunit;

    private Integer specDosetype;

    private Integer specDose;

    private String specDoseuintstr;

    private Integer specUsagefunc;

    private String specUsages;

    private String instructions;

    private Integer chargeFlag;

    private Integer managementFlag;
    private Integer medicareFlag;
    private Integer bidType;
    private String bidDate;
    private String bidExpiredDate;
    private Integer bidFlag;
    private Double salePrice;
    private Long salePriceCurrencyId;
    private String salePriceCurrencyName;
    private Long regId;
    
    private String regNo;
    private Long goodsUnitId;
    private String goodsUnitName;
    private Double bidPrice;

    private Long bidPriceCurrencyId;
    
    private String bidPriceCurrencyName;
    private Double unitPrice;

    private Long unitPriceCurrencyId;
    
    private String unitPriceCurrencyName;
    private String inviteNo;

    private String inviteFileno;
    private Integer repeatNo;
    private Double repeatPrice;

    private Double repeatPay;

    private Long addBy;

    private String addName;

    private String addTime;

    private Long lastEditBy;

    private String lastEditName;

    private String lastEditTime;

    private Integer sourceFlag;

    private Integer delFlag;

    public Long getSpecId() {
        return specId;
    }

    public void setSpecId(Long specId) {
        this.specId = specId;
    }

    public Long getSysId() {
        return sysId;
    }

    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }

    public Integer getAreaId() {
        return areaId;
    }

    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    public Long getClassId() {
        return classId;
    }

    public void setClassId(Long classId) {
        this.classId = classId;
    }

    public Long getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    public Integer getGoodsType() {
        return goodsType;
    }

    public void setGoodsType(Integer goodsType) {
        this.goodsType = goodsType;
    }

    public String getSpecGuid() {
        return specGuid;
    }

    public void setSpecGuid(String specGuid) {
        this.specGuid = specGuid;
    }

    public String getSpecNo() {
        return specNo;
    }

    public void setSpecNo(String specNo) {
        this.specNo = specNo;
    }

    public String getSpecBarcode() {
        return specBarcode;
    }

    public void setSpecBarcode(String specBarcode) {
        this.specBarcode = specBarcode;
    }

    public Integer getSpecBarcodeType() {
        return specBarcodeType;
    }

    public void setSpecBarcodeType(Integer specBarcodeType) {
        this.specBarcodeType = specBarcodeType;
    }

    public String getSpecModel() {
        return specModel;
    }

    public void setSpecModel(String specModel) {
        this.specModel = specModel;
    }

    public String getSpecCommonName() {
        return specCommonName;
    }

    public void setSpecCommonName(String specCommonName) {
        this.specCommonName = specCommonName;
    }

    public String getSpecNameEn() {
        return specNameEn;
    }

    public void setSpecNameEn(String specNameEn) {
        this.specNameEn = specNameEn;
    }

    public String getSpecNameCn() {
        return specNameCn;
    }

    public void setSpecNameCn(String specNameCn) {
        this.specNameCn = specNameCn;
    }

    public String getSpecPackage() {
        return specPackage;
    }

    public void setSpecPackage(String specPackage) {
        this.specPackage = specPackage;
    }

    public String getSpecBigpackstr() {
        return specBigpackstr;
    }

    public void setSpecBigpackstr(String specBigpackstr) {
        this.specBigpackstr = specBigpackstr;
    }

    public String getSpecBasepackstr() {
        return specBasepackstr;
    }

    public void setSpecBasepackstr(String specBasepackstr) {
        this.specBasepackstr = specBasepackstr;
    }

    public Integer getSpecBasepackNo() {
        return specBasepackNo;
    }

    public void setSpecBasepackNo(Integer specBasepackNo) {
        this.specBasepackNo = specBasepackNo;
    }

    public String getSpecBasepackNote() {
        return specBasepackNote;
    }

    public void setSpecBasepackNote(String specBasepackNote) {
        this.specBasepackNote = specBasepackNote;
    }

    public String getSpecMinipackstr() {
        return specMinipackstr;
    }

    public void setSpecMinipackstr(String specMinipackstr) {
        this.specMinipackstr = specMinipackstr;
    }

    public Double getSpecMiniunit() {
        return specMiniunit;
    }

    public void setSpecMiniunit(Double specMiniunit) {
        this.specMiniunit = specMiniunit;
    }

    public Integer getSpecDosetype() {
        return specDosetype;
    }

    public void setSpecDosetype(Integer specDosetype) {
        this.specDosetype = specDosetype;
    }

    public Integer getSpecDose() {
        return specDose;
    }

    public void setSpecDose(Integer specDose) {
        this.specDose = specDose;
    }

    public String getSpecDoseuintstr() {
        return specDoseuintstr;
    }

    public void setSpecDoseuintstr(String specDoseuintstr) {
        this.specDoseuintstr = specDoseuintstr;
    }

    public Integer getSpecUsagefunc() {
        return specUsagefunc;
    }

    public void setSpecUsagefunc(Integer specUsagefunc) {
        this.specUsagefunc = specUsagefunc;
    }

    public String getSpecUsages() {
        return specUsages;
    }

    public void setSpecUsages(String specUsages) {
        this.specUsages = specUsages;
    }

    public String getInstructions() {
        return instructions;
    }

    public void setInstructions(String instructions) {
        this.instructions = instructions;
    }

    public Integer getChargeFlag() {
        return chargeFlag;
    }

    public void setChargeFlag(Integer chargeFlag) {
        this.chargeFlag = chargeFlag;
    }

    public Integer getManagementFlag() {
        return managementFlag;
    }

    public void setManagementFlag(Integer managementFlag) {
        this.managementFlag = managementFlag;
    }

    public Integer getMedicareFlag() {
        return medicareFlag;
    }

    public void setMedicareFlag(Integer medicareFlag) {
        this.medicareFlag = medicareFlag;
    }

    public Integer getBidType() {
        return bidType;
    }

    public void setBidType(Integer bidType) {
        this.bidType = bidType;
    }

    public String getBidDate() {
        return bidDate;
    }

    public void setBidDate(String bidDate) {
        this.bidDate = bidDate;
    }

    public String getBidExpiredDate() {
        return bidExpiredDate;
    }

    public void setBidExpiredDate(String bidExpiredDate) {
        this.bidExpiredDate = bidExpiredDate;
    }

    public Integer getBidFlag() {
        return bidFlag;
    }

    public void setBidFlag(Integer bidFlag) {
        this.bidFlag = bidFlag;
    }

    public Double getSalePrice() {
        return salePrice;
    }

    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }

    public Long getSalePriceCurrencyId() {
        return salePriceCurrencyId;
    }

    public void setSalePriceCurrencyId(Long salePriceCurrencyId) {
        this.salePriceCurrencyId = salePriceCurrencyId;
    }

    public Long getRegId() {
        return regId;
    }

    public void setRegId(Long regId) {
        this.regId = regId;
    }

    public Long getGoodsUnitId() {
        return goodsUnitId;
    }

    public void setGoodsUnitId(Long goodsUnitId) {
        this.goodsUnitId = goodsUnitId;
    }

    public Double getBidPrice() {
        return bidPrice;
    }

    public void setBidPrice(Double bidPrice) {
        this.bidPrice = bidPrice;
    }

    public Long getBidPriceCurrencyId() {
        return bidPriceCurrencyId;
    }

    public void setBidPriceCurrencyId(Long bidPriceCurrencyId) {
        this.bidPriceCurrencyId = bidPriceCurrencyId;
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Long getUnitPriceCurrencyId() {
        return unitPriceCurrencyId;
    }

    public void setUnitPriceCurrencyId(Long unitPriceCurrencyId) {
        this.unitPriceCurrencyId = unitPriceCurrencyId;
    }

    public String getInviteNo() {
        return inviteNo;
    }

    public void setInviteNo(String inviteNo) {
        this.inviteNo = inviteNo;
    }

    public String getInviteFileno() {
        return inviteFileno;
    }

    public void setInviteFileno(String inviteFileno) {
        this.inviteFileno = inviteFileno;
    }

    public Integer getRepeatNo() {
        return repeatNo;
    }

    public void setRepeatNo(Integer repeatNo) {
        this.repeatNo = repeatNo;
    }

    public Double getRepeatPrice() {
        return repeatPrice;
    }

    public void setRepeatPrice(Double repeatPrice) {
        this.repeatPrice = repeatPrice;
    }

    public Double getRepeatPay() {
        return repeatPay;
    }

    public void setRepeatPay(Double repeatPay) {
        this.repeatPay = repeatPay;
    }

    public Long getAddBy() {
        return addBy;
    }

    public void setAddBy(Long addBy) {
        this.addBy = addBy;
    }

    public String getAddName() {
        return addName;
    }

    public void setAddName(String addName) {
        this.addName = addName;
    }

    public String getAddTime() {
        return addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public Long getLastEditBy() {
        return lastEditBy;
    }

    public void setLastEditBy(Long lastEditBy) {
        this.lastEditBy = lastEditBy;
    }

    public String getLastEditName() {
        return lastEditName;
    }

    public void setLastEditName(String lastEditName) {
        this.lastEditName = lastEditName;
    }

    public String getLastEditTime() {
        return lastEditTime;
    }

    public void setLastEditTime(String lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    public Integer getSourceFlag() {
        return sourceFlag;
    }

    public void setSourceFlag(Integer sourceFlag) {
        this.sourceFlag = sourceFlag;
    }

    public Integer getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    public String getRegNo() {
        return regNo;
    }

    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public String getSalePriceCurrencyName() {
        return salePriceCurrencyName;
    }

    public void setSalePriceCurrencyName(String salePriceCurrencyName) {
        this.salePriceCurrencyName = salePriceCurrencyName;
    }

    public String getGoodsUnitName() {
        return goodsUnitName;
    }

    public void setGoodsUnitName(String goodsUnitName) {
        this.goodsUnitName = goodsUnitName;
    }

    public String getBidPriceCurrencyName() {
        return bidPriceCurrencyName;
    }

    public void setBidPriceCurrencyName(String bidPriceCurrencyName) {
        this.bidPriceCurrencyName = bidPriceCurrencyName;
    }

    public String getUnitPriceCurrencyName() {
        return unitPriceCurrencyName;
    }

    public void setUnitPriceCurrencyName(String unitPriceCurrencyName) {
        this.unitPriceCurrencyName = unitPriceCurrencyName;
    }

}
