package com.aek.persistence.mysql.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import com.aek.persistence.oracle.beans.DataErrorInfo;
import com.aek.persistence.oracle.beans.ZyChargeInterface;
import com.mb.common.dal.BaseMapper;

/**
 * 病人收费信息Mapper
 * @author Lanpz
 * @date 2016-08-04
 * @source Generated by MySQL2Java
 */
@Repository
public interface MZyChargeInterfaceMapper extends BaseMapper<ZyChargeInterface, Integer> {

    /**
     * 获取病人收费信息
     * @param zyChargeInfo
     * @return List<ZyChargeInfo>
     */
    List<ZyChargeInterface> getList(@Param("begin")int begin, @Param("end")int end);

    /**
     * 通过id获取信息
     * @param errorList
     * @return
     */
    List<ZyChargeInterface> getListByIds(List<DataErrorInfo> errorList);

    /**
     * 获取总数信息
     * @return
     */
    int getCount();

}
