package com.aek.persistence.mysql.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.HisUserInfo;
import com.mb.common.dal.BaseMapper;

/**
 * HIS职工人员视图Mapper
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
@Repository
public interface MHisUserInfoMapper extends BaseMapper<HisUserInfo, Integer> {

    /**
     * 获取HIS职工人员视图
     * @param oracleList 
     * @param hisUserInfo
     * @return List<HisUserInfo>
     */
    List<HisUserInfo> getAll(List<HisUserInfo> oracleList);

    /**
     * 批量修改HIS职工人员视图
     * @param addList
     * @return
     */
    int addList(List<HisUserInfo> addList);
    
    /**
     * 批量修改HIS职工人员视图
     * @param updateList
     * @return
     */
    int updateList(List<HisUserInfo> updateList);

}
