package com.aek.persistence.mysql.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.SdHplStockOut;
import com.mb.common.dal.BaseMapper;

/**
 * 库房正常出库记录表。Mapper
 * @author Lanpz
 * @date 2016-12-20
 * @source Generated by MySQL2Java
 */
@Repository
public interface MSdHplStockOutMapper extends BaseMapper<SdHplStockOut, Integer> {
    List<SdHplStockOut> getOutList(@Param("begin")Integer begin, @Param("end")Integer end, @Param("dateFlag")Integer dateFlag);
}
