package com.aek.persistence.mysql.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.SdHplStockOutItems;
import com.mb.common.dal.BaseMapper;

/**
 * 库房出库明细表。Mapper
 * @author Lanpz
 * @date 2016-12-20
 * @source Generated by MySQL2Java
 */
@Repository
public interface MSdHplStockOutItemsMapper extends BaseMapper<SdHplStockOutItems, Integer> {
    List<SdHplStockOutItems> getItemList(@Param("begin")Integer begin, @Param("end")Integer end, @Param("dateFlag") Integer dateFlag);
}
