package com.aek.persistence.mysql.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.HisFeeInfo;
import com.mb.common.dal.BaseMapper;

/**
 * 医疗收费代码视图Mapper
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
@Repository
public interface MHisFeeInfoMapper extends BaseMapper<HisFeeInfo, Integer> {

    /**
     * 获取mysql中医疗收费代码视图
     * @param feeOracleList 
     * @param hisFeeInfo
     * @return List<HisFeeInfo>
     */
    List<HisFeeInfo> getAll(List<HisFeeInfo> feeOracleList);

    /**
     * 批量添加操作
     * @param updateList
     * @return
     */
    int updateList(List<HisFeeInfo> updateList);

    /**
     * 批量修改操作
     * @param addList
     * @return
     */
    int addList(List<HisFeeInfo> addList);

}
