package com.aek.persistence.oracle.beans;

import com.mb.common.dal.object.AbstractDO;

/**
 * 库房出库明细表。模型
 * @author Lanpz
 * @date 2016-12-20
 * @source Generated by MySQL2Java
 */
public class SdHplStockOutItems extends AbstractDO {

    /**
     * 
     */
    private Long itemId;

    /**
     * 
     */
    private Integer areaId;

    /**
     * 
     */
    private Long sysId;

    /**
     * 
     */
    private Long whId;
    
    private String whName;

    /**
     * 
     */
    private Long whSiteId;
    
    private String whSiteName;
    private Long formId;

    /**
     * 
     */
    private Integer itemIndex;

    /**
     * 
     */
    private Long exchangeId;

    /**
     * 
     */
    private Long specId;
    
    private String specModel;

    /**
     * 
     */
    private String goodsName;

    /**
     * 
     */
    private String commonName;

    /**
     * 
     */
    private String specSize;

    /**
     * 
     */
    private String regNo;

    /**
     * 
     */
    private String specUnit;

    /**
     * 
     */
    private Double unitPrice;

    /**
     * 
     */
    private String specPackage;

    /**
     * 
     */
    private Long splId;
    
    private String splName;

    /**
     * 
     */
    private Long facId;
    
    private String facName;

    /**
     * 
     */
    private String factoryAddr;

    /**
     * 
     */
    private String specBrand;

    /**
     * 
     */
    private Integer stockOutQty;

    /**
     * 
     */
    private Double stockPrice;

    /**
     * 
     */
    private Integer stockGiftQty;

    /**
     * 
     */
    private Integer stockReturnQty;

    /**
     * 
     */
    private Integer stockOldQty;

    /**
     * 
     */
    private Double stockAmount;

    /**
     * 
     */
    private Integer specBarcodeType;

    /**
     * 
     */
    private Long barcodeId;

    /**
     * 
     */
    private String barcodeStr;

    /**
     * 
     */
    private String batchNo;

    /**
     * 
     */
    private String productDate;

    /**
     * 
     */
    private String expiredDate;

    /**
     * 
     */
    private String sterilizeNo;

    /**
     * 
     */
    private String sterilizeDate;

    /**
     * 
     */
    private Integer lockFlag;

    /**
     * 
     */
    private Long reqItemId;

    /**
     * 
     */
    private String stockCheckReason;

    /**
     * 
     */
    private Long redItemId;

    /**
     * 
     */
    private Long addBy;

    /**
     * 
     */
    private String addName;

    /**
     * 
     */
    private Long lastEditBy;

    /**
     * 
     */
    private String lastEditName;

    /**
     * 
     */
    private String lastEditTime;

    /**
     * 
     */
    private Long curId;

    /**
     * 
     */
    private Long accountType;

    /**
     * 
     */
    private Long calcType;

    /**
     * 
     */
    private Integer stockRedQty;

    /**
     * 
     */
    private Integer stockAccQty;

    /**
     * 
     */
    private Integer stockBudgetQty;

    /**
     * 
     */
    private Integer stockCancelQty;

    /**
     * 
     */
    private Integer stockBackQty;

    /**
     * 
     */
    private Long accItemId;

    /**
     * 
     */
    private Long budgetItemId;

    /**
     * 
     */
    private Long cancelItemId;

    /**
     * 
     */
    private Long returnItemId;

    /**
     * 
     */
    private Long backItemId;
    
    private String addTime;
    
    private Integer delFlag;
    
    private String accountTypeName;
    
    private String calcTypeName;

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public Integer getAreaId() {
        return areaId;
    }

    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    public Long getSysId() {
        return sysId;
    }

    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }

    public Long getWhId() {
        return whId;
    }

    public void setWhId(Long whId) {
        this.whId = whId;
    }

    public Long getWhSiteId() {
        return whSiteId;
    }

    public void setWhSiteId(Long whSiteId) {
        this.whSiteId = whSiteId;
    }

    public Long getFormId() {
        return formId;
    }

    public void setFormId(Long formId) {
        this.formId = formId;
    }

    public Integer getItemIndex() {
        return itemIndex;
    }

    public void setItemIndex(Integer itemIndex) {
        this.itemIndex = itemIndex;
    }

    public Long getExchangeId() {
        return exchangeId;
    }

    public void setExchangeId(Long exchangeId) {
        this.exchangeId = exchangeId;
    }

    public Long getSpecId() {
        return specId;
    }

    public void setSpecId(Long specId) {
        this.specId = specId;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public String getCommonName() {
        return commonName;
    }

    public void setCommonName(String commonName) {
        this.commonName = commonName;
    }

    public String getSpecSize() {
        return specSize;
    }

    public void setSpecSize(String specSize) {
        this.specSize = specSize;
    }

    public String getRegNo() {
        return regNo;
    }

    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }

    public String getSpecUnit() {
        return specUnit;
    }

    public void setSpecUnit(String specUnit) {
        this.specUnit = specUnit;
    }

    public Double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public String getSpecPackage() {
        return specPackage;
    }

    public void setSpecPackage(String specPackage) {
        this.specPackage = specPackage;
    }

    public Long getSplId() {
        return splId;
    }

    public void setSplId(Long splId) {
        this.splId = splId;
    }

    public Long getFacId() {
        return facId;
    }

    public void setFacId(Long facId) {
        this.facId = facId;
    }

    public String getFactoryAddr() {
        return factoryAddr;
    }

    public void setFactoryAddr(String factoryAddr) {
        this.factoryAddr = factoryAddr;
    }

    public String getSpecBrand() {
        return specBrand;
    }

    public void setSpecBrand(String specBrand) {
        this.specBrand = specBrand;
    }

    public Integer getStockOutQty() {
        return stockOutQty;
    }

    public void setStockOutQty(Integer stockOutQty) {
        this.stockOutQty = stockOutQty;
    }

    public Double getStockPrice() {
        return stockPrice;
    }

    public void setStockPrice(Double stockPrice) {
        this.stockPrice = stockPrice;
    }

    public Integer getStockGiftQty() {
        return stockGiftQty;
    }

    public void setStockGiftQty(Integer stockGiftQty) {
        this.stockGiftQty = stockGiftQty;
    }

    public Integer getStockReturnQty() {
        return stockReturnQty;
    }

    public void setStockReturnQty(Integer stockReturnQty) {
        this.stockReturnQty = stockReturnQty;
    }

    public Integer getStockOldQty() {
        return stockOldQty;
    }

    public void setStockOldQty(Integer stockOldQty) {
        this.stockOldQty = stockOldQty;
    }

    public Double getStockAmount() {
        return stockAmount;
    }

    public void setStockAmount(Double stockAmount) {
        this.stockAmount = stockAmount;
    }

    public Integer getSpecBarcodeType() {
        return specBarcodeType;
    }

    public void setSpecBarcodeType(Integer specBarcodeType) {
        this.specBarcodeType = specBarcodeType;
    }

    public Long getBarcodeId() {
        return barcodeId;
    }

    public void setBarcodeId(Long barcodeId) {
        this.barcodeId = barcodeId;
    }

    public String getBarcodeStr() {
        return barcodeStr;
    }

    public void setBarcodeStr(String barcodeStr) {
        this.barcodeStr = barcodeStr;
    }

    public String getBatchNo() {
        return batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public String getProductDate() {
        return productDate;
    }

    public void setProductDate(String productDate) {
        this.productDate = productDate;
    }

    public String getExpiredDate() {
        return expiredDate;
    }

    public void setExpiredDate(String expiredDate) {
        this.expiredDate = expiredDate;
    }

    public String getSterilizeNo() {
        return sterilizeNo;
    }

    public void setSterilizeNo(String sterilizeNo) {
        this.sterilizeNo = sterilizeNo;
    }

    public String getSterilizeDate() {
        return sterilizeDate;
    }

    public void setSterilizeDate(String sterilizeDate) {
        this.sterilizeDate = sterilizeDate;
    }

    public Integer getLockFlag() {
        return lockFlag;
    }

    public void setLockFlag(Integer lockFlag) {
        this.lockFlag = lockFlag;
    }

    public Long getReqItemId() {
        return reqItemId;
    }

    public void setReqItemId(Long reqItemId) {
        this.reqItemId = reqItemId;
    }

    public String getStockCheckReason() {
        return stockCheckReason;
    }

    public void setStockCheckReason(String stockCheckReason) {
        this.stockCheckReason = stockCheckReason;
    }

    public Long getRedItemId() {
        return redItemId;
    }

    public void setRedItemId(Long redItemId) {
        this.redItemId = redItemId;
    }

    public Long getAddBy() {
        return addBy;
    }

    public void setAddBy(Long addBy) {
        this.addBy = addBy;
    }

    public String getAddName() {
        return addName;
    }

    public void setAddName(String addName) {
        this.addName = addName;
    }

    public Long getLastEditBy() {
        return lastEditBy;
    }

    public void setLastEditBy(Long lastEditBy) {
        this.lastEditBy = lastEditBy;
    }

    public String getLastEditName() {
        return lastEditName;
    }

    public void setLastEditName(String lastEditName) {
        this.lastEditName = lastEditName;
    }

    public String getLastEditTime() {
        return lastEditTime;
    }

    public void setLastEditTime(String lastEditTime) {
        this.lastEditTime = lastEditTime;
    }

    public Long getCurId() {
        return curId;
    }

    public void setCurId(Long curId) {
        this.curId = curId;
    }

    public Long getAccountType() {
        return accountType;
    }

    public void setAccountType(Long accountType) {
        this.accountType = accountType;
    }

    public Long getCalcType() {
        return calcType;
    }

    public void setCalcType(Long calcType) {
        this.calcType = calcType;
    }

    public Integer getStockRedQty() {
        return stockRedQty;
    }

    public void setStockRedQty(Integer stockRedQty) {
        this.stockRedQty = stockRedQty;
    }

    public Integer getStockAccQty() {
        return stockAccQty;
    }

    public void setStockAccQty(Integer stockAccQty) {
        this.stockAccQty = stockAccQty;
    }

    public Integer getStockBudgetQty() {
        return stockBudgetQty;
    }

    public void setStockBudgetQty(Integer stockBudgetQty) {
        this.stockBudgetQty = stockBudgetQty;
    }

    public Integer getStockCancelQty() {
        return stockCancelQty;
    }

    public void setStockCancelQty(Integer stockCancelQty) {
        this.stockCancelQty = stockCancelQty;
    }

    public Integer getStockBackQty() {
        return stockBackQty;
    }

    public void setStockBackQty(Integer stockBackQty) {
        this.stockBackQty = stockBackQty;
    }

    public Long getAccItemId() {
        return accItemId;
    }

    public void setAccItemId(Long accItemId) {
        this.accItemId = accItemId;
    }

    public Long getBudgetItemId() {
        return budgetItemId;
    }

    public void setBudgetItemId(Long budgetItemId) {
        this.budgetItemId = budgetItemId;
    }

    public Long getCancelItemId() {
        return cancelItemId;
    }

    public void setCancelItemId(Long cancelItemId) {
        this.cancelItemId = cancelItemId;
    }

    public Long getReturnItemId() {
        return returnItemId;
    }

    public void setReturnItemId(Long returnItemId) {
        this.returnItemId = returnItemId;
    }

    public Long getBackItemId() {
        return backItemId;
    }

    public void setBackItemId(Long backItemId) {
        this.backItemId = backItemId;
    }

    public String getAddTime() {
        return addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    public Integer getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

    public String getSplName() {
        return splName;
    }

    public void setSplName(String splName) {
        this.splName = splName;
    }

    public String getFacName() {
        return facName;
    }

    public void setFacName(String facName) {
        this.facName = facName;
    }

    public String getSpecModel() {
        return specModel;
    }

    public void setSpecModel(String specModel) {
        this.specModel = specModel;
    }

    public String getWhName() {
        return whName;
    }

    public void setWhName(String whName) {
        this.whName = whName;
    }

    public String getWhSiteName() {
        return whSiteName;
    }

    public void setWhSiteName(String whSiteName) {
        this.whSiteName = whSiteName;
    }

    public String getAccountTypeName() {
        return accountTypeName;
    }

    public void setAccountTypeName(String accountTypeName) {
        this.accountTypeName = accountTypeName;
    }

    public String getCalcTypeName() {
        return calcTypeName;
    }

    public void setCalcTypeName(String calcTypeName) {
        this.calcTypeName = calcTypeName;
    }

    @Override
    public String toString() {
        return "SdHplStockOutItems [itemId=" + itemId + ", areaId=" + areaId + ", sysId=" + sysId + ", whId=" + whId
                + ", whName=" + whName + ", whSiteId=" + whSiteId + ", whSiteName=" + whSiteName + ", formId=" + formId
                + ", itemIndex=" + itemIndex + ", exchangeId=" + exchangeId + ", specId=" + specId + ", specModel="
                + specModel + ", goodsName=" + goodsName + ", commonName=" + commonName + ", specSize=" + specSize
                + ", regNo=" + regNo + ", specUnit=" + specUnit + ", unitPrice=" + unitPrice + ", specPackage="
                + specPackage + ", splId=" + splId + ", splName=" + splName + ", facId=" + facId + ", facName="
                + facName + ", factoryAddr=" + factoryAddr + ", specBrand=" + specBrand + ", stockOutQty=" + stockOutQty
                + ", stockPrice=" + stockPrice + ", stockGiftQty=" + stockGiftQty + ", stockReturnQty=" + stockReturnQty
                + ", stockOldQty=" + stockOldQty + ", stockAmount=" + stockAmount + ", specBarcodeType="
                + specBarcodeType + ", barcodeId=" + barcodeId + ", barcodeStr=" + barcodeStr + ", batchNo=" + batchNo
                + ", productDate=" + productDate + ", expiredDate=" + expiredDate + ", sterilizeNo=" + sterilizeNo
                + ", sterilizeDate=" + sterilizeDate + ", lockFlag=" + lockFlag + ", reqItemId=" + reqItemId
                + ", stockCheckReason=" + stockCheckReason + ", redItemId=" + redItemId + ", addBy=" + addBy
                + ", addName=" + addName + ", lastEditBy=" + lastEditBy + ", lastEditName=" + lastEditName
                + ", lastEditTime=" + lastEditTime + ", curId=" + curId + ", accountType=" + accountType + ", calcType="
                + calcType + ", stockRedQty=" + stockRedQty + ", stockAccQty=" + stockAccQty + ", stockBudgetQty="
                + stockBudgetQty + ", stockCancelQty=" + stockCancelQty + ", stockBackQty=" + stockBackQty
                + ", accItemId=" + accItemId + ", budgetItemId=" + budgetItemId + ", cancelItemId=" + cancelItemId
                + ", returnItemId=" + returnItemId + ", backItemId=" + backItemId + ", addTime=" + addTime
                + ", delFlag=" + delFlag + ", accountTypeName=" + accountTypeName + ", calcTypeName=" + calcTypeName
                + "]";
    }
    
}
