package com.aek.persistence.oracle.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.aek.persistence.oracle.beans.HisFeeInfo;
import com.mb.common.dal.BaseMapper;

/**
 * 医疗收费代码视图Mapper
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
@Repository
public interface OHisFeeInfoMapper extends BaseMapper<HisFeeInfo, Integer> {

    /**
     * 获取医疗收费代码视图
     * @param hisFeeInfo
     * @return List<HisFeeInfo>
     */
    List<HisFeeInfo> getAll(@Param("begin")int begin, @Param("end")int end);

}
