package com.aek.persistence.oracle.beans;

import com.mb.common.dal.object.AbstractDO;

/**
 * 科室信息视图模型
 * 
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
public class HisDeptInfo extends AbstractDO {

    /**
     * 科室类别ID
     */
    private Integer deptTypeId;

    /**
     * 科室类别名称
     */
    private String deptTypeName;

    /**
     * 科室代码
     */
    private String deptNo;

    /**
     * 科室名称
     */
    private String deptName;

    /**
     * 科室名称拼音码
     */
    private String deptNamePy;

    /**
     * 科室名称五笔码
     */
    private String deptNameWb;

    /**
     * 上级科室代码
     */
    private String deptParentNo;

    /**
     * 科室层级
     */
    private Integer deptLevel;

    /**
     * 作废标志
     */
    private Integer delFlag;

    /**
     * 取值 科室类别ID
     * 
     * @return 科室类别ID
     */
    public Integer getDeptTypeId() {
        return this.deptTypeId;
    }

    /**
     * 赋值 科室类别ID
     * 
     * @param deptTypeId
     *            科室类别ID
     */
    public void setDeptTypeId(Integer deptTypeId) {
        this.deptTypeId = deptTypeId;
    }

    /**
     * 取值 科室类别名称
     * 
     * @return 科室类别名称
     */
    public String getDeptTypeName() {
        return this.deptTypeName;
    }

    /**
     * 赋值 科室类别名称
     * 
     * @param deptTypeName
     *            科室类别名称
     */
    public void setDeptTypeName(String deptTypeName) {
        this.deptTypeName = deptTypeName;
    }

    /**
     * 取值 科室代码
     * 
     * @return 科室代码
     */
    public String getDeptNo() {
        return this.deptNo;
    }

    /**
     * 赋值 科室代码
     * 
     * @param deptNo
     *            科室代码
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * 取值 科室名称
     * 
     * @return 科室名称
     */
    public String getDeptName() {
        return this.deptName;
    }

    /**
     * 赋值 科室名称
     * 
     * @param deptName
     *            科室名称
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * 取值 科室名称拼音码
     * 
     * @return 科室名称拼音码
     */
    public String getDeptNamePy() {
        return this.deptNamePy;
    }

    /**
     * 赋值 科室名称拼音码
     * 
     * @param deptNamePy
     *            科室名称拼音码
     */
    public void setDeptNamePy(String deptNamePy) {
        this.deptNamePy = deptNamePy;
    }

    /**
     * 取值 科室名称五笔码
     * 
     * @return 科室名称五笔码
     */
    public String getDeptNameWb() {
        return this.deptNameWb;
    }

    /**
     * 赋值 科室名称五笔码
     * 
     * @param deptNameWb
     *            科室名称五笔码
     */
    public void setDeptNameWb(String deptNameWb) {
        this.deptNameWb = deptNameWb;
    }

    /**
     * 取值 上级科室代码
     * 
     * @return 上级科室代码
     */
    public String getDeptParentNo() {
        return this.deptParentNo;
    }

    /**
     * 赋值 上级科室代码
     * 
     * @param deptParentNo
     *            上级科室代码
     */
    public void setDeptParentNo(String deptParentNo) {
        this.deptParentNo = deptParentNo;
    }

    /**
     * 取值 科室层级
     * 
     * @return 科室层级
     */
    public Integer getDeptLevel() {
        return this.deptLevel;
    }

    /**
     * 赋值 科室层级
     * 
     * @param deptLevel
     *            科室层级
     */
    public void setDeptLevel(Integer deptLevel) {
        this.deptLevel = deptLevel;
    }

    public Integer getDelFlag() {
        return delFlag;
    }

    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }

}
