package com.aek.persistence.oracle.beans;

import java.util.Date;

import com.mb.common.dal.object.AbstractDO;

/**
 * 手术病人信息视图模型
 * 
 * @author Lanpz
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
public class HisInpatientInfo extends AbstractDO {
    /**
     * 病案号
     */
    private String inpatientNo;

    /**
     * 病人姓名
     */
    private String patientName;

    /**
     * 床位号
     */
    private String bedNo;

    /**
     * 手术名称
     */
    private String operationName;

    /**
     * 手术日期
     */
    private Date operationDate;

    /**
     * 发生日期
     */
    private Date happenDate;

    /**
     * 手术医生ID
     */
    private String operationDoctorNo;

    /**
     * 手术医生名称
     */
    private String operationDoctorName;

    /**
     * 病人所属科室ID
     */
    private String deptNo;

    /**
     * 病人所属科室名称
     */
    private String deptName;

    /**
     * 住院号
     */
    private Integer patientNo;

    /**
     * 出院标志
     */
    private Integer outFlag;

    /**
     * 通知单手术代码
     */
    private String newOperationNo;

    /**
     * 通知单手术名称
     */
    private String newOperationName;

    /**
     * 手术id(唯一码)
     */
    private Integer operationId;

    /**
     * 出院日期
     */
    private Date outDate;

    /**
     * 婴儿标志
     */
    private Integer infantFlag;

    /**
     * 当前病区代码
     */
    private String currentDeptNo;

    /**
     * 当前病区
     */
    private String currentDeptName;

    /**
     * 手术间名称
     */
    private String operationRoomName;

    /**
     * 台次
     */
    private String operationIndex;

    /**
     * 性别
     */
    private Integer patientSex;

    /**
     * 年龄
     */
    private Integer patientAge;
    
    
    private Integer patientDay;

    /**
     * 诊断
     */
    private String operationDiagnose;

    /**
     * 感染诊断
     */
    private String sickInfectFlag;

    public String getInpatientNo() {
        return inpatientNo;
    }

    public void setInpatientNo(String inpatientNo) {
        this.inpatientNo = inpatientNo;
    }

    /**
     * 取值 病人姓名
     * 
     * @return 病人姓名
     */
    public String getPatientName() {
        return this.patientName;
    }

    /**
     * 赋值 病人姓名
     * 
     * @param patientName
     *            病人姓名
     */
    public void setPatientName(String patientName) {
        this.patientName = patientName;
    }

    /**
     * 取值 床位号
     * 
     * @return 床位号
     */
    public String getBedNo() {
        return this.bedNo;
    }

    /**
     * 赋值 床位号
     * 
     * @param bedNo
     *            床位号
     */
    public void setBedNo(String bedNo) {
        this.bedNo = bedNo;
    }

    /**
     * 取值 手术名称
     * 
     * @return 手术名称
     */
    public String getOperationName() {
        return this.operationName;
    }

    /**
     * 赋值 手术名称
     * 
     * @param operationName
     *            手术名称
     */
    public void setOperationName(String operationName) {
        this.operationName = operationName;
    }

    /**
     * 取值 手术医生ID
     * 
     * @return 手术医生ID
     */
    public String getOperationDoctorNo() {
        return this.operationDoctorNo;
    }

    /**
     * 赋值 手术医生ID
     * 
     * @param operationDoctorNo
     *            手术医生ID
     */
    public void setOperationDoctorNo(String operationDoctorNo) {
        this.operationDoctorNo = operationDoctorNo;
    }

    /**
     * 取值 手术医生名称
     * 
     * @return 手术医生名称
     */
    public String getOperationDoctorName() {
        return this.operationDoctorName;
    }

    /**
     * 赋值 手术医生名称
     * 
     * @param operationDoctorName
     *            手术医生名称
     */
    public void setOperationDoctorName(String operationDoctorName) {
        this.operationDoctorName = operationDoctorName;
    }

    /**
     * 取值 病人所属科室ID
     * 
     * @return 病人所属科室ID
     */
    public String getDeptNo() {
        return this.deptNo;
    }

    /**
     * 赋值 病人所属科室ID
     * 
     * @param deptNo
     *            病人所属科室ID
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * 取值 病人所属科室名称
     * 
     * @return 病人所属科室名称
     */
    public String getDeptName() {
        return this.deptName;
    }

    /**
     * 赋值 病人所属科室名称
     * 
     * @param deptName
     *            病人所属科室名称
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * 取值 住院号
     * 
     * @return 住院号
     */
    public Integer getPatientNo() {
        return this.patientNo;
    }

    /**
     * 赋值 住院号
     * 
     * @param patientNo
     *            住院号
     */
    public void setPatientNo(Integer patientNo) {
        this.patientNo = patientNo;
    }

    /**
     * 取值 出院标志
     * 
     * @return 出院标志
     */
    public Integer getOutFlag() {
        return this.outFlag;
    }

    /**
     * 赋值 出院标志
     * 
     * @param outFlag
     *            出院标志
     */
    public void setOutFlag(Integer outFlag) {
        this.outFlag = outFlag;
    }

    /**
     * 取值 通知单手术代码
     * 
     * @return 通知单手术代码
     */
    public String getNewOperationNo() {
        return this.newOperationNo;
    }

    /**
     * 赋值 通知单手术代码
     * 
     * @param newOperationNo
     *            通知单手术代码
     */
    public void setNewOperationNo(String newOperationNo) {
        this.newOperationNo = newOperationNo;
    }

    /**
     * 取值 通知单手术名称
     * 
     * @return 通知单手术名称
     */
    public String getNewOperationName() {
        return this.newOperationName;
    }

    /**
     * 赋值 通知单手术名称
     * 
     * @param newOperationName
     *            通知单手术名称
     */
    public void setNewOperationName(String newOperationName) {
        this.newOperationName = newOperationName;
    }

    /**
     * 取值 手术id(唯一码)
     * 
     * @return 手术id(唯一码)
     */
    public Integer getOperationId() {
        return this.operationId;
    }

    /**
     * 赋值 手术id(唯一码)
     * 
     * @param operationId
     *            手术id(唯一码)
     */
    public void setOperationId(Integer operationId) {
        this.operationId = operationId;
    }

    /**
     * 取值 婴儿标志
     * 
     * @return 婴儿标志
     */
    public Integer getInfantFlag() {
        return this.infantFlag;
    }

    /**
     * 赋值 婴儿标志
     * 
     * @param infantFlag
     *            婴儿标志
     */
    public void setInfantFlag(Integer infantFlag) {
        this.infantFlag = infantFlag;
    }

    /**
     * 取值 当前病区代码
     * 
     * @return 当前病区代码
     */
    public String getCurrentDeptNo() {
        return this.currentDeptNo;
    }

    /**
     * 赋值 当前病区代码
     * 
     * @param currentDeptNo
     *            当前病区代码
     */
    public void setCurrentDeptNo(String currentDeptNo) {
        this.currentDeptNo = currentDeptNo;
    }

    /**
     * 取值 当前病区
     * 
     * @return 当前病区
     */
    public String getCurrentDeptName() {
        return this.currentDeptName;
    }

    /**
     * 赋值 当前病区
     * 
     * @param currentDeptName
     *            当前病区
     */
    public void setCurrentDeptName(String currentDeptName) {
        this.currentDeptName = currentDeptName;
    }

    /**
     * 取值 手术间名称
     * 
     * @return 手术间名称
     */
    public String getOperationRoomName() {
        return this.operationRoomName;
    }

    /**
     * 赋值 手术间名称
     * 
     * @param operationRoomName
     *            手术间名称
     */
    public void setOperationRoomName(String operationRoomName) {
        this.operationRoomName = operationRoomName;
    }

    /**
     * 取值 台次
     * 
     * @return 台次
     */
    public String getOperationIndex() {
        return this.operationIndex;
    }

    /**
     * 赋值 台次
     * 
     * @param operationIndex
     *            台次
     */
    public void setOperationIndex(String operationIndex) {
        this.operationIndex = operationIndex;
    }

    /**
     * 取值 性别
     * 
     * @return 性别
     */
    public Integer getPatientSex() {
        return this.patientSex;
    }

    /**
     * 赋值 性别
     * 
     * @param patientSex
     *            性别
     */
    public void setPatientSex(Integer patientSex) {
        this.patientSex = patientSex;
    }

    /**
     * 取值 年龄
     * 
     * @return 年龄
     */
    public Integer getPatientAge() {
        return this.patientAge;
    }

    /**
     * 赋值 年龄
     * 
     * @param patientAge
     *            年龄
     */
    public void setPatientAge(Integer patientAge) {
        this.patientAge = patientAge;
    }

    /**
     * 取值 诊断
     * 
     * @return 诊断
     */
    public String getOperationDiagnose() {
        return this.operationDiagnose;
    }

    /**
     * 赋值 诊断
     * 
     * @param operationDiagnose
     *            诊断
     */
    public void setOperationDiagnose(String operationDiagnose) {
        this.operationDiagnose = operationDiagnose;
    }

    /**
     * 取值 感染诊断
     * 
     * @return 感染诊断
     */
    public String getSickInfectFlag() {
        return this.sickInfectFlag;
    }

    /**
     * 赋值 感染诊断
     * 
     * @param sickInfectFlag
     *            感染诊断
     */
    public void setSickInfectFlag(String sickInfectFlag) {
        this.sickInfectFlag = sickInfectFlag;
    }

    public Date getOperationDate() {
        return operationDate;
    }

    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    public Date getHappenDate() {
        return happenDate;
    }

    public void setHappenDate(Date happenDate) {
        this.happenDate = happenDate;
    }

    public Date getOutDate() {
        return outDate;
    }

    public void setOutDate(Date outDate) {
        this.outDate = outDate;
    }

    public Integer getPatientDay() {
        return patientDay;
    }

    public void setPatientDay(Integer patientDay) {
        this.patientDay = patientDay;
    }

}
